### ISSUE TITLE
Atlas of minimal size 

### ISSUE THREAD

**Issue by Belorus** [huxingyi/squeezer#1]
Possibility to create atlas of minimal possible size would be great!

**Comment by huxingyi** [comment]
Good idea,  do you have any thoughts on how to implement that? Try 64x64  128x64 128x128 256x128 256x256 … one by one until successfully containing all sprites?
Pull request is VERY welcome :P

**Comment by Belorus** [comment]
Right, looks like growing bruteforce + alpha crop will do the job :)
